### Needs to execute `01-ReferenceDFs.ipynb` to be executed first

Reads from this:
- `gs_extractions_raw.json`
- `year_scope_df.json`

In [12]:
import pandas as pd

In [13]:
gs_extractions_raw  = pd.read_json("gs_extractions_raw.json")
year_scope_df       = pd.read_json("year_scope_df.json")

In [16]:
gs_extractions_raw.head()

,report_name,status,scopes_present,years_present,year,scope,page,value,unit,unit_normalized,...,unit_m1,unit_m2,unit_i1,unit_i2,label_t1,label_t2,label_m1,label_m2,label_i1,label_i2
0,acuity brands inc_2022_report,complete,"[1, 2lb, 2mb, 3]",[2022],2013,1,NaN,NaN,NaN,NaN,...,None,None,None,None,None,None,None,None,None,None
1,acuity brands inc_2022_report,complete,"[1, 2lb, 2mb, 3]",[2022],2014,1,NaN,NaN,NaN,NaN,...,None,None,None,None,None,None,None,None,None,None
2,acuity brands inc_2022_report,complete,"[1, 2lb, 2mb, 3]",[2022],2015,1,NaN,NaN,NaN,NaN,...,None,None,None,None,None,None,None,None,None,None
3,acuity brands inc_2022_report,complete,"[1, 2lb, 2mb, 3]",[2022],2016,1,NaN,NaN,NaN,NaN,...,None,None,None,None,None,None,None,None,None,None
4,acuity brands inc_2022_report,complete,"[1, 2lb, 2mb, 3]",[2022],2017,1,NaN,NaN,NaN,NaN,...,None,None,None,None,None,None,None,None,None,None

In [17]:
year_scope_df.head()

                     report_name  year            scopes
0  acuity brands inc_2022_report  2022  [1, 2lb, 2mb, 3]
1            addtech_2022_report  2019       [1, 2lb, 3]
2            addtech_2022_report  2020  [1, 2lb, 2mb, 3]
3            addtech_2022_report  2021  [1, 2lb, 2mb, 3]
4            aixtron_2020_report  2019       [1, 2lb, 3]